### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated for XBox live

### ISSUE THREAD

**Issue by almagest** [ToxicFrog/bltool#30]
Steam imports work fine, but when trying to do the same for XBox I get:

```
java -jar bltool.jar --from xboxlive --to backloggery --xbox-name <xbl name> --bl-name <name> --bl-pass <pass>
Exception in thread "main" javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at clj_http.core$request.invoke(core.clj:277)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__1651.invoke(client.clj:633)
	at clj_http.client$wrap_lower_case_headers$fn__1648.invoke(client.clj:624)
	at clj_http.client$wrap_query_params$fn__1589.invoke(client.clj:502)
	at clj_http.client$wrap_basic_auth$fn__1594.invoke(client.clj:518)
	at clj_http.client$wrap_oauth$fn__1598.invoke(client.clj:528)
	at clj_http.client$wrap_user_info$fn__1603.invoke(client.clj:541)
	at clj_http.client$wrap_url$fn__1635.invoke(client.clj:599)
	at clj_http.client$wrap_redirects$fn__1462.invoke(client.clj:189)
	at clj_http.client$wrap_decompression$fn__1484.invoke(client.clj:258)
	at clj_http.client$wrap_input_coercion$fn__1538.invoke(client.clj:393)
	at clj_http.client$wrap_additional_header_parsing$fn__1559.invoke(client.clj:436)
	at clj_http.client$wrap_output_coercion$fn__1529.invoke(client.clj:347)
	at clj_http.client$wrap_exceptions$fn__1443.invoke(client.clj:141)
	at clj_http.client$wrap_accept$fn__1569.invoke(client.clj:463)
	at clj_http.client$wrap_accept_encoding$fn__1575.invoke(client.clj:478)
	at clj_http.client$wrap_content_type$fn__1564.invoke(client.clj:454)
	at clj_http.client$wrap_form_params$fn__1613.invoke(client.clj:565)
	at clj_http.client$wrap_nested_params$fn__1631.invoke(client.clj:589)
	at clj_http.client$wrap_method$fn__1608.invoke(client.clj:548)
	at clj_http.cookies$wrap_cookies$fn__298.invoke(cookies.clj:121)
	at clj_http.links$wrap_links$fn__328.invoke(links.clj:50)
	at clj_http.client$wrap_unknown_host$fn__1640.invoke(client.clj:608)
	at clj_http.client$get.doInvoke(client.clj:715)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at bltool.data.xboxlive$xboxapi_request.invoke(xboxlive.clj:37)
	at bltool.data.xboxlive$fn__2272.invoke(xboxlive.clj:58)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at bltool.core$execute.invoke(core.clj:75)
	at bltool.core$_main$fn__2310.invoke(core.clj:114)
	at bltool.core$_main.doInvoke(core.clj:111)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at bltool.core.main(Unknown Source)

**Comment by ToxicFrog** [comment]
This might be related to #21, but as I don't have an XBL account I have no way of testing or resolving this.

**Comment by almagest** [comment]
It doesn't require a password for the XBL account so I'm happy to provide mine if needed.

**Comment by Ackis** [comment]
@ToxicFrog If you have a microsoft account, you have an xbox account.

You can populate some free games if you have access to Windows 8/10.  There's a bunch of Microsoft casual games that you can play for free.

Might be easier for you to test?
